/// Flutter icons GatherCustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GatherCustomIcons
///      fonts:
///       - asset: fonts/GatherCustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GatherCustomIcons {
  GatherCustomIcons._();

  static const _kFontFam = 'GatherCustomIcons';
  static const _kFontPkg = null;

  static const IconData gather = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playstation = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xbox = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData computer = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData casual = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData competitive = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helicopter = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData others = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
